In [1]:
import os
import numpy as np
import pandas as pd

# csv_file = '0910_BD.csv'
csv_file = 'BD2019_without_insurance_20190101-20190831.csv'
excel_file = '0910_BD.xlsx'

column_names = ['结算方编码', '结算方名称', '券池编码', '券池名称', '券码', 
                '券类型', '券使用类型', '券结算方式', 'csc发放形式', 'csc活动分类名称', 
                '订单日期', '省', '市', '门店', '订单号', 
                '订单车牌', '券面值', '用券结算价', '用券直接收入', '用券转化服务数', 
                '用券转化收入', '售券结算金额', '售券日期', '售券订单号', '售券支付金额']

# column_names = ['结算方', '券池编码', '券池名称', '券码', '券类型', '券使用类型', '结算方式', '用券日期', '省', '市', '门店', '用券订单号', '用券车牌', '券面值', '用券结算价', '用券直接收入', '用券转化服务数', '用券转化收入', '售券结算金额', '售券日期', '售券订单号', '售券支付金额']
data_type = {'结算方编码': np.string_, '结算方名称': np.string_, '券池编码': np.string_, '券池名称': np.string_, '券码': np.string_, 
             '券类型': np.string_, '券使用类型': np.string_, '券结算方式': np.string_, 'csc发放形式': np.string_, 'csc活动分类名称': np.string_, 
             '订单日期': np.string_, '省': np.string_, '市': np.string_, '门店': np.string_, '订单号': np.string_, 
             '订单车牌': np.string_, '券面值': np.float32, '用券结算价': np.float32, '用券直接收入': np.float32, '用券转化服务数': np.int16, 
             '用券转化收入': np.float32, '售券结算金额': np.float32, '售券日期': np.string_, '售券订单号': np.string_, '售券支付金额': np.float32}
df = pd.read_csv(os.path.join(os.getcwd(), 'csv', csv_file), names=column_names, skiprows=1, dtype=data_type)
# df = pd.read_excel(os.path.join(os.getcwd(), 'excel', excel_file))
# df.describe()

In [2]:
df.describe()

,券面值,用券结算价,用券直接收入,用券转化服务数,用券转化收入,售券结算金额,售券支付金额
count,164012.000000,164012.000000,164012.000000,164012.000000,164012.000000,164012.0,164012.0
mean,25.961506,17.034845,3.818390,0.126533,16.392225,0.0,0.0
std,17.277815,15.605346,35.944824,4.302932,998.006897,0.0,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
25%,25.000000,18.000000,0.000000,0.000000,0.000000,0.0,0.0
50%,25.000000,18.000000,0.000000,0.000000,0.000000,0.0,0.0
75%,25.000000,18.000000,0.000000,0.000000,0.000000,0.0,0.0
max,1490.000000,3128.000000,1490.000000,872.000000,302967.031250,0.0,0.0

In [5]:
# export csv
#, quoting=1
df.to_csv(os.path.join(os.getcwd(), 'csv', 'all_0910.csv'), encoding='utf_8_sig', sep=',')

In [3]:
settlement_group = df.groupby(['结算方', '券使用类型', '结算方式'])
for g, g_df in settlement_group:
    print(g)

('?宁波力拓信息科技有限公司?', '全额兑换券', '用券结算')
('ETCP', '全额兑换券', '用券结算')
('上海中油三新石油有限公司', '全额兑换券', '用券结算')
('上海优方信息科技服务股份有限公司', '全额兑换券', '用券结算')
('上海传龙文化传播有限公司', '全额兑换券', '售券结算')
('上海国际酒类现代商贸服务功能区发展管理中心', '全额兑换券', '用券结算')
('上海墨瑞实业发展有限公司', '全额兑换券', '用券结算')
('上海墨瑞实业发展有限公司', '部分兑换券', '用券结算')
('上海外服商务管理有限公司', '全额兑换券', '用券结算')
('上海好腾豹进出口有限公司', '全额兑换券', '售券结算')
('上海安吉旧机动车经纪有限公司', '全额兑换券', '用券结算')
('上海攸宁', '全额兑换券', '用券结算')
('上海无忧汽车驾驶服务有限公司', '部分兑换券', '用券结算')
('上海易骋汽车服务有限公司', '全额兑换券', '用券结算')
('上海昶晁信息技术有限公司', '全额兑换券', '售券结算')
('上海杜瓦信息技术有限公司', '全额兑换券', '用券结算')
('上海歆颖房地产经纪有限公司', '全额兑换券', '售券结算')
('上海汽车工业机动车置换服务有限公司', '全额兑换券', '用券结算')
('上海汽车集团股份有限公司乘用车分公司工会', '全额兑换券', '售券结算')
('上海润桂荇信息科技服务有限公司 ', '全额兑换券', '售券结算')
('上海润桂荇信息科技服务有限公司 ', '全额兑换券', '用券结算')
('上海满嘉电子商务股份有限公司', '全额兑换券', '用券结算')
('上海赛可出行科技服务有限公司', '全额兑换券', '用券结算')
('上海赛可电子商务有限公司', '全额兑换券', '售券结算')
('上海赛可电子商务有限公司', '全额兑换券', '用券结算')
('上海车享文化传播有限公司', '全额兑换券', '用券结算')
('上海通贸国际供应链管理有限公司', '全额兑换券', '售券结算')
('上海酉辰信息技术有限公司', '全额兑换券', '售券结算')
('上海酉辰信息技术有限公司', '全额兑换券', '用券结算')
('上海韵泰会务有限公司', '全额兑换券', '用券结算')
('世纪恒通', '全额兑换券', '用券结算')
('中信银行股份有限公司信用卡中心', '全额兑换券', '用券结算')
('中国人寿财产保险股份有限公司上海市分公司', '全额兑换券', '用券结算')
('中国太平洋保险股份有限公司四川分公司', '全额兑换券', '用券结算')
('中国工商银行股份有限公司上海市第一支行', '部分兑换券', '用券结算')
('中国建设银行股份有限公司上海武康路支行', '全额兑换券', '售券结算')
('中国石油天然气股份有限公司广州润滑油销售分公司', '全额兑换券', '售券结算')
('中国铁塔股份有限公司沈阳市分公司', '全额兑换券', '售券结算')
('中石油山西太原销售分公司', '全额兑换券', '用券结算')
('中银保险', '全额兑换券', '用券结算')
('中银保险', '部分兑换券', '用券结算')
('中银保险有限公司上海分公司', '全额兑换券', '用券结算')
('华浦南瑞科技重庆有限公司', '全额兑换券', '售券结算')
('南京保倍电子商务有限公司', '全额兑换券', '售券结算')
('南京淼焱垚文化传媒有限公司', '全额兑换券', '用券结算')
('南京通华汽车销售有限公司', '全额兑换券', '售券结算')
('唐山市天下行汽车租赁有限公司', '全额兑换券', '售券结算')
('四川联联旅游公司', '全额兑换券', '用券结算')
('宁波海曙阿林棋牌室', '全额兑换券', '售券结算')
('宁波盛联汽车服务有限公司', '全额兑换券', '售券结算')
('希杰（上海）商贸有限公司', '全额兑换券', '售券结算')
('平安保险', '全额兑换券', '用券结算')
('平安国际融资租赁有限公司', '全额兑换券', '售券结算')
('成都欢喜伏志网络信息有限公司', '全额兑换券', '用券结算')
('成都翼联科技有限公司', '全额兑换券', '用券结算')
('新共赢信息科技服务有限公司', '全额兑换券', '用券结算')
('新力科技集团有限公司', '全额兑换券', '用券结算')
('无锡艺丰文化传媒有限公司', '全额兑换券', '售券结算')
('最会保', '全额兑换券', '用券结算')
('杭州大搜车汽车服务有限公司', '全额兑换券', '用券结算')
('杭州安卡网络技术股份有限公司 ', '全额兑换券', '售券结算')
('杭州安卡网络技术股份有限公司 ', '全额兑换券', '用券结算')
('杭州禄品文化创意有限公司', '全额兑换券', '用券结算')
('杭州行不行互联网科技有限公司  ', '全额兑换券', '用券结算')
('毛豆汽车服务（天津）有限公司', '全额兑换券', '用券结算')
('江苏南通农村商业银行股份有限公司', '全额兑换券', '用券结算')
('河南一家网络科技有限公司', '全额兑换券', '售券结算')
('河南嵩云网络科技有限公司', '全额兑换券', '用券结算')
('河南汇之和电子科技有限公司', '全额兑换券', '用券结算')
('浙江绍兴瑞丰农村商业银行股份有限公司', '全额兑换券', '用券结算')
('盛大汽车', '全额兑换券', '用券结算')
('苏州北冥有鱼汽车服务公司', '全额兑换券', '用券结算')
('苏州北冥有鱼汽车服务公司', '部分兑换券', '用券结算')
('车享', '全额兑换券', '用券结算')
('车享家-线上app', '全额兑换券', '售券结算')
('车享汽车俱乐部（上海）有限公司', '全额兑换券', '售券结算')
('车享汽车俱乐部（上海）有限公司', '全额兑换券', '用券结算')
('车享汽车俱乐部（上海）有限公司', '部分兑换券', '用券结算')
('车惠车网络科技有限公司', '全额兑换券', '用券结算')
('车智互联（北京）科技有限公司  ', '全额兑换券', '用券结算')
('车点点', '全额兑换券', '用券结算')
('辽宁兴隆电子商务有限公司', '全额兑换券', '用券结算')
('重庆博影世纪文化传播有限公司', '全额兑换券', '用券结算')
('重庆新影通科技有限公司', '全额兑换券', '用券结算')
('重庆沁格文化传媒有限公司', '全额兑换券', '售券结算')
('重庆砗宜宝商务信息咨询有限公司', '全额兑换券', '售券结算')
('重庆砗宜宝商务信息咨询有限公司', '全额兑换券', '用券结算')
('重庆福晓智慧科技有限公司', '全额兑换券', '用券结算')
('金鑫珠宝连锁企业洛阳区白店', '全额兑换券', '售券结算')
('雅晴国际电子商务有限公司', '全额兑换券', '用券结算')

In [ ]:
df[df["结算方"]=="盛大汽车"].to_csv(os.path.join(os.getcwd(), 'csv', 'sdqc0910.csv'), encoding='utf_8_sig', sep=',')

In [19]:
df[~df['售券订单号'].isnull()]['售券订单号']

344       190605101001050377172
675       190822101001052970165
1276      190428101001048915417
1363      190909101001053455370
1464      190228101001046586144
1748      190723101001052167693
2198      190110101001043978752
2239      190515101001049652487
2287      190130101001045235292
2842      190515101001049660493
3406      190628101001051540327
3518      190716101001051977326
3929      190611101001050780880
4250      190609101001050674301
4496      190419101001048664913
4535      190101101001043607179
4887      190524101001049978041
5066      190418101001048619585
5177      190525101001049994927
5438      190718101001052034591
6117      190728101001052302904
6349      190426101001048859739
6507      190719101001052055719
6850      190426101001048854350
7096      190823101001052993308
7514      190509101001049434693
7613      190731101001052391487
7672      190418101001048619585
8741      190517101001049725955
8979      190308101001046850442
                  ...
345131    190430101001049080988
345754    190106101001043859744
345936    190404101001048075558
346435    190123101001044625194
348403    190606101001050490497
349887    190827101001053113145
349950    190809101001052594847
349951    190606101001050492308
350271    190909101001053459833
350435    190126101001044982712
351041    190622101001051382447
351289    190214101001045566809
351356    190517101001049726488
352245    190226101001046446316
352284    190510101001049460263
352509    190813101001052692119
353548    190107101001043893388
353549    190617101001051085400
354109    190611101001050791279
354193    190402101001047967919
354281    190425101001048815618
354439    190704101001051705385
354474    190721101001052098252
354479    190131101001045279379
354547    190323101001047538778
354823    190314101001047099073
355347    190414101001048473161
355495    190725101001052220618
355741    190118101001044345056
355847    190731101001052377414
Name: 售券订单号, Length: 1044, dtype: object

In [ ]:
settlement_array = df["结算方"].unique()
len(settlement_array)

# for s in settlement:
#     data[data["结算方"]==s].to_csv('.\csv\%s.csv' % s, encoding='utf_8_sig')